title: "Innerverz 기술 블로그"
email: innerverz@innerverz.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo-innerverz.png'
favicon: 'assets/images/favicon.ico'
author: 이유경
paginate: 30
disqus: 'invz-ai'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-EB9PSDRL50

# Authors
authors:
  류원종:
    name: 류원종
    display_name: 류원종
    avatar: 'assets/images/sal.png'
    email: "1zong2@innerverz.com"
    web: ""
    twitter: ""
    description: "류원종입니다."
  정정영:
    name: 정정영
    display_name: 정정영
    avatar: 'assets/images/john.png'
    email: ""
    web: ""
    twitter: ""
    description: "정정영입니다."
  이유경:
    name: 이유경
    display_name: 이유경
    avatar: 'assets/images/john.png'
    email: "ukok828@gmail.com"
    web: ""
    twitter: ""
    description: "이유경입니다."

# Social
social:
  instagram: ""
  facebook: ""
  twitter: ""

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-toc

defaults:
  - scope:
      path: ""
    values:
      toc: true

toc:
ordered_list: true
list_class: my-list-class
sublist_class: my-sublist-class
.my-list-class {
  list-style-type: upper-alpha;
}

.my-sublist-class: {
  list-style-type: lower-alpha;
}