title: "Innerverz Tech Blog"
email: innerverz@innerverz.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo-innerverz.png'
# favicon: 'assets/images/favicon.ico'
author: 이유경
paginate: 30
disqus: 'invz-ai'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-EB9PSDRL50

google_site_verification: 4U8vQQVpssfeN8GleEZhw0DOc4ox1sOBPHlduNkQGOQ

# Authors
authors:
  류원종:
    name: 류원종
    display_name: 류원종
    avatar: 'assets/images/sal.png'
    email: "1zong2@innerverz.com"
    web: ""
    twitter: ""
    description: "류원종입니다."
  정정영:
    name: 정정영
    display_name: 정정영
    avatar: 'assets/images/john.png'
    email: "pensee0.0a@innerverz.com"
    web: ""
    twitter: ""
    description: "정정영입니다."
  이유경:
    name: 이유경
    display_name: 이유경
    avatar: 'assets/images/john.png'
    email: "ukok828@gmail.com"
    web: ""
    twitter: ""
    description: "이유경입니다."
  김준혁:
    name: 김준혁
    display_name: 김준혁
    avatar: 'assets/images/jk.jpg'
    email: "junejoon.kim@innerverz.com"
    web: ""
    twitter: ""
    description: "Football Enthusiast"
  조우영:
    name: 조우영
    display_name: 조우영
    avatar: 'assets/images/sal.png'
    email: "chowy333@innerverz.com"
    web: ""
    twitter: ""
    description: "조우영입니다."
   김재훈:
    name: 김재훈
    display_name: 김재훈
    avatar: 'assets/images/source_m2.png'
    email: "smoked22@innerverz.com"
    web: ""
    twitter: ""
    description: "김재훈입니다."

# Social
social:
  instagram: ""
  facebook: ""
  twitter: ""

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives

